name: workflows
on:
  workflow_call:
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      MAIL_USERNAME:
        required: true
      MAIL_PASSWORD:
        required: true
  
jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract last commit timestamp
        id: commit-date
        run: echo "::set-output name=COMMIT_DATE::$(git log -1 --pretty=%ci | sed -e s'/[-:+]//'g -e s'/ /_/'g)"

      - name: Generate metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
          tags: ${{ steps.commit-date.outputs.COMMIT_DATE }}
          flavor: latest=true

      - name: Build container
        uses: docker/build-push-action@v2.10.0
        with:
          load: true
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Read test setup (start)
        id: test_setup_start
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/workflows/test_setup.start

      - name: Read test setup (stop)
        id: test_setup_stop
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/workflows/test_setup.stop

      - name: Test new container
        id: test
        run: |
          echo "::group::Start container"
          echo "Running container with name test_subject"
          docker run --detach --name test_subject ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
          echo "::endgroup::"
          echo "::group::Test container"
          echo "Waiting for 10 seconds for container initializatzion"
          sleep 10
          echo "Showing container logs"
          output=$(docker logs test_subject 2>&1)
          echo "$output" ; output="${output//'%'/'%25'}" ; output="${output//$'\n'/'%0A'}" ; output="${output//$'\r'/'%0D'}" ; echo "::set-output name=LOGS::$output" 
          echo "Showing container stats"
          output=$(docker exec test_subject sh -c "ps -ef || echo 'PS command not available!'")
          echo "$output" ; output="${output//'%'/'%25'}" ; output="${output//$'\n'/'%0A'}" ; output="${output//$'\r'/'%0D'}" ; echo "::set-output name=STATS::$output" 
          echo "::endgroup::"
          echo "::group::Stop container"
          echo "Stopping container"
          docker stop test_subject
          docker rm test_subject
          echo "::endgroup::"

      - name: Send test results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.dschinghis-kahn.net
          server_port: 25
          username:  ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: coding@dschinghis-kahn.net
          to: coding@dschinghis-kahn.net
          subject: "Test results for build of ${{ github.repository }}"
          body: "Here are the results of the test of the recent build:\n\nLogs:\n${{ steps.test.outputs.LOGS }}\n\nStats:\n${{ steps.test.outputs.STATS }}\n"

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          context: .
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Sync readme and description
        if: ${{ github.event_name != 'pull_request' }}
        uses: meeDamian/sync-readme@v1.0.6
        continue-on-error: true
        with:
          user: ${{ secrets.DOCKER_HUB_USERNAME }}
          pass: ${{ secrets.DOCKER_HUB_PASSWORD }}
          slug: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
          description: true
