name: workflows
on:
  workflow_call:
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
  
jobs:
  test-build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container
        uses: docker/build-push-action@v2.10.0
        with:
          load: true
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Test new container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
          options: --rm

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Sync readme and description
        if: ${{ github.event_name != 'pull_request' }}
        uses: meeDamian/sync-readme@v1.0.6
        continue-on-error: true
        with:
          user: ${{ secrets.DOCKER_HUB_USERNAME }}
          pass: ${{ secrets.DOCKER_HUB_PASSWORD }}
          slug: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
          description: true
